apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
helmCharts:
  - name: postgresql
    releaseName: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.1.2
    namespace: dev
    valuesFile: postgresql-values.yaml

