global:
  persistence:
    enabled: false
auth:
  postgresPassword: postgres
primary:
  initdb:
    scripts:
      00_init_script.sh: |
        export PGPASSWORD=$POSTGRES_PASSWORD
        psql -U postgres -c 'CREATE DATABASE "cncf-demo";'
